// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package db

import (
	"context"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateChatParams struct {
	UserID string `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.UserID, arg.Title)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (chat_id, role, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, role, content, created_at
`

type CreateChatMessageParams struct {
	ChatID  string `json:"chat_id"`
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.ChatID, arg.Role, arg.Content)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE id = $1 AND user_id = $2
`

type DeleteChatParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteChat(ctx context.Context, arg DeleteChatParams) error {
	_, err := q.db.ExecContext(ctx, deleteChat, arg.ID, arg.UserID)
	return err
}

const getAllChatsByUserID = `-- name: GetAllChatsByUserID :many
SELECT id, user_id, title, created_at, updated_at FROM chats
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) GetAllChatsByUserID(ctx context.Context, userID string) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getAllChatsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, user_id, title, created_at, updated_at FROM chats
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetChatByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetChatByID(ctx context.Context, arg GetChatByIDParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, arg.ID, arg.UserID)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id, chat_id, role, content, created_at FROM chat_messages
WHERE chat_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetChatMessages(ctx context.Context, chatID string) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatTitle = `-- name: UpdateChatTitle :exec
UPDATE chats
SET title = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3
`

type UpdateChatTitleParams struct {
	Title  string `json:"title"`
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UpdateChatTitle(ctx context.Context, arg UpdateChatTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateChatTitle, arg.Title, arg.ID, arg.UserID)
	return err
}
