// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteChat(ctx context.Context, arg DeleteChatParams) error
	DeletePasswordReset(ctx context.Context, email string) error
	GetAllChatsByUserID(ctx context.Context, userID string) ([]Chat, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetChatByID(ctx context.Context, arg GetChatByIDParams) (Chat, error)
	GetChatMessages(ctx context.Context, chatID string) ([]ChatMessage, error)
	GetPasswordReset(ctx context.Context, email string) (GetPasswordResetRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	SavePasswordReset(ctx context.Context, arg SavePasswordResetParams) error
	UpdateChatTitle(ctx context.Context, arg UpdateChatTitleParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
