// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password, username)
VALUES ($1, $2, $3)
RETURNING id, email, password, username, is_profile_completed, created_at, updated_at
`

type CreateUserParams struct {
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Username sql.NullString `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Username,
		&i.IsProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePasswordReset = `-- name: DeletePasswordReset :exec
DELETE FROM password_resets
WHERE email = $1
`

func (q *Queries) DeletePasswordReset(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordReset, email)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email FROM users
`

type GetAllUsersRow struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllUsersRow{}
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT otp, expires_at FROM password_resets
WHERE email = $1
`

type GetPasswordResetRow struct {
	Otp       string    `json:"otp"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetPasswordReset(ctx context.Context, email string) (GetPasswordResetRow, error) {
	row := q.db.QueryRowContext(ctx, getPasswordReset, email)
	var i GetPasswordResetRow
	err := row.Scan(&i.Otp, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, username, is_profile_completed, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Username,
		&i.IsProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, username, is_profile_completed, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Username,
		&i.IsProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savePasswordReset = `-- name: SavePasswordReset :exec
INSERT INTO password_resets (email, otp, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (email)
DO UPDATE SET
    otp = EXCLUDED.otp,
    expires_at = EXCLUDED.expires_at,
    created_at = NOW()
`

type SavePasswordResetParams struct {
	Email     string    `json:"email"`
	Otp       string    `json:"otp"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) SavePasswordReset(ctx context.Context, arg SavePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, savePasswordReset, arg.Email, arg.Otp, arg.ExpiresAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $1, updated_at = NOW()
WHERE email = $2
`

type UpdateUserPasswordParams struct {
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.Email)
	return err
}
